### ISSUE TITLE
菜单在后台删除后,前台还留在那里.

### ISSUE THREAD

**Issue by tuutoo** [kuizuo/kz-vue-admin#2]
重现: 添加一个测试菜单, 然后删除它. 会发现菜单还在界面上.

原因是menu的index.vue里缺少了rowKey
![截屏2022-05-26 23 48 12](https://user-images.githubusercontent.com/9068314/170524785-b65a09a9-fa9b-4161-b62c-d05428f65430.png)

**Comment by kuizuo** [comment]
![image](https://user-images.githubusercontent.com/61005888/170526622-b6958b3e-dcc4-4707-9b4e-b632c9839ca8.png)

After I delete, I should reload
