### ISSUE TITLE
关于树状结构的表

### ISSUE THREAD

**Issue by Sunny-liaokai** [kuizuo/kz-vue-admin#3]
```typescript
import {
  Column,
  Entity,
  PrimaryGeneratedColumn,
  Tree,
  TreeChildren,
  TreeParent,
} from 'typeorm';

@Entity('tree')
@Tree('materialized-path')
export class TreeEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column()
  name: string;

  @TreeChildren({
    cascade: ['insert', 'update', 'remove', 'soft-remove', 'recover'],
  })
  children: TreeEntity[];

  @TreeParent()
  parent: TreeEntity;
}
````
就是我想定义一个这样的实体树结构的表，这样就不用递归生成树了，但是我看你项目好像是后端这边递归生成菜单树，我这种定义请问一下你有没有用过，在用的时候遇到过一个这么问题，删除树结构的某一项报外键关联错误

**Comment by kuizuo** [comment]
typeorm定义树结构是比较简单的，但typeorm关系会涉及到外键约束（物理层限制）。外键也确实方便，我之前就是使用typeorm一对多，多对多的关系，数据定义与获取简单方便，同时不必编写过多约束代码。但我非常讨厌外键，尤其是在数据删除的与数据迁移，外键会带来一些复杂性。所以就没再使用typeorm的关系，而通过代码层面来进行数据约束。

回到这个树结构，我的做法都是将查询到的**数据列表通过递归来生成树结构**，逻辑层面实现的。当然你也可以使用typeorm的树实体，但你需要考虑外键所带来的约束，这就需要结合你所遇到的实际问题来处理了。
